- hosts: all
  remote_user: akupchenko
  become: yes
  tasks:
        - sysctl:
            name: net.ipv4.ip_nonlocal_bind
            value: 1
            sysctl_set: yes
            state: present
            reload: yes
