- hosts: all
  remote_user: akupchenko
  become: yes
  tasks:
#    - name: Install keepalived (Centos)
#      yum: name=keepalived state=present
#      when: ansible_os_family == "RedHat"
#      tags: keepalived

    - name: Upload configuration keepalived
      template: src=keepalived.conf.j2 dest=/etc/keepalived/keepalived.conf
      tags: keepalived

#    - name: Start keepalived
#      service: name=keepalived state=restarted
#      tags: keepalived
